#!/bin/bash

fpaths=`echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sort`

for file in $fpaths
do
  if [ -f "$file" ]; then
	base=${file%.*}
	ext=${file##*.}
	if [ "$ext" == "exr" ]; then
	    pfsin $file | pfstmo_fattal02 | pfsgamma --gamma 2.6 | pfsout "$base"_fattal.png
	fi
  fi
done

