#!/bin/bash
gst-launch-0.10 filesrc location=$1 ! decodebin ! ffmpegcolorspace ! queue ! jp462bayer ! "video/x-raw-bayer, width=(int)1280, height=(int)720, format=(string)grbg" ! queue ! bayer2rgb2 method=1 ! queue ! ffmpegcolorspace ! xvimagesink

