#!/bin/bash

fpaths=`echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sort`

for file in $fpaths
do
  if [ -f "$file" ]; then
	base=${file%.*}
	ext=${file##*.}
	if [ "$ext" == "RW2" ]; then
	    dcraw -e $file
	fi
  fi
done
#mkdir rw2
#mv *.RW2 ./rw2

