#!/bin/bash

fpaths=`echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sort`

for file in $fpaths
do
  if [ -f "$file" ]; then
        base=${file%.*}
	    convert -resize 1280x720 $file $base-720.jpg
  fi
done

