#!/bin/bash
fpaths=`echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sort`

for file in $fpaths
do
  if [ -f "$file" ]; then
	base=${file%.*}
	mkdir mkv
    mv *.mkv mkv/
    mkdir mov
    mv *.mov mov/   
  fi
done


