#!/bin/bash
fpaths=`echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sort`

for file in $fpaths
do
  if [ -f "$file" ]; then
	base=${file%.*}
	mkdir tiff
    mv *.tiff tiff/
    mkdir dng
    mv *.dng dng/   
  fi
done


