#!/bin/bash

fpaths=`echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sort`

for file in $fpaths
do
  if [ -f "$file" ]; then
        base=${file%.*}
	    convert -crop 1920x950+0+118 $file $base-c.jpg
  fi
done

