#!/bin/bash

fpaths=`echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sort`

for file in $fpaths
do
  if [ -f "$file" ]; then
        base=${file%.*}
	    convert -crop -640+0 $file $base-a.jpg
        convert -crop +640+0 $file $base-b.jpg
  fi
done

